[tool.poetry]
name = "genpod"
version = "0.1.0"
authors = ["anonymous"]
description = ""
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pddl = { path = "./pddl" }
dlplan = { path = "./dlplan" }
clingo = "*"
pygraphviz = "*"
tqdm = "*"
setuptools = "*"
filelock = "*"
frozendict = "*"
pyyaml = "*"
mergedeep = "^1.3.4"


[tool.poetry.group.dev.dependencies]
flake8 = "*"
pytest = "*"
ipython = "^7.0"
mypy = "^1.15.0"
types-tqdm = "^4.67.0.20250301"
types-pyyaml = "^6.0.12.20241230"
isort = "^6.0.1"
black = "^25.1.0"

[tool.mypy]

[[tool.mypy.overrides]]
module = ["pddl.*", "dlplan.*", "mergedeep.*"]
ignore_missing_imports = true

[tool.isort]
line_length = 119
profile = "black"

[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
