(define (problem p3x3)
    (:hidden (gold-at p3-3) (pit-at p3-1) (wumpus-at p2-2))
    (:hidden (gold-at p3-3) (pit-at p3-2) (wumpus-at p2-3))
    (:hidden (gold-at p1-1) (wumpus-at p3-1) (pit-at p1-3))
    (:hidden (wumpus-at p3-3) (gold-at p2-2) (pit-at p3-1))
    (:hidden (pit-at p2-2) (wumpus-at p2-3) (gold-at p2-1))
    (:hidden (gold-at p3-3) (pit-at p3-1) (wumpus-at p2-2))
    (:hidden (wumpus-at p3-1) (gold-at p1-1) (pit-at p3-2))
    (:hidden (pit-at p1-3) (gold-at p1-2) (wumpus-at p2-3))
    (:hidden (wumpus-at p3-3) (gold-at p1-1) (pit-at p2-2))
    (:hidden (pit-at p3-1) (wumpus-at p1-3) (gold-at p2-2))
    (:hidden (gold-at p2-1) (wumpus-at p3-3) (pit-at p2-2))
    (:hidden (pit-at p3-2) (gold-at p3-1) (wumpus-at p2-2))
    (:hidden (wumpus-at p3-2) (pit-at p3-3) (gold-at p2-2))
    (:hidden (gold-at p1-3) (pit-at p3-3) (wumpus-at p3-1))
    (:hidden (gold-at p2-2) (pit-at p3-2) (wumpus-at p3-1))
    (:hidden (wumpus-at p2-3) (gold-at p1-3) (pit-at p3-3))
    (:hidden (wumpus-at p3-1) (pit-at p2-2) (gold-at p3-3))
    (:hidden (pit-at p2-3) (wumpus-at p1-3) (gold-at p1-1))
    (:hidden (wumpus-at p3-1) (gold-at p2-3) (pit-at p1-3))
    (:hidden (pit-at p2-3) (wumpus-at p2-2) (gold-at p1-3))
)
