(define (problem bs-p9)
    (:hidden (secret p8))
    (:hidden (secret p7))
    (:hidden (secret p6))
    (:hidden (secret p5))
    (:hidden (secret p4))
    (:hidden (secret p3))
    (:hidden (secret p2))
    (:hidden (secret p1))
    (:hidden (secret p0))
)
