(define (problem p3x4)
    (:hidden (wumpus-at p1-2))
    (:hidden (wumpus-at p1-3))
    (:hidden (wumpus-at p1-4))
    (:hidden (wumpus-at p2-1))
    (:hidden (wumpus-at p2-2))
    (:hidden (wumpus-at p2-3))
    (:hidden (wumpus-at p2-4))
    (:hidden (wumpus-at p3-1))
    (:hidden (wumpus-at p3-2))
    (:hidden (wumpus-at p3-3))
    (:hidden (wumpus-at p3-4))
)
