(define (problem p2x3)
    (:hidden (gold-at p1-1) (pit-at p2-2) (wumpus-at p3-1))
    (:hidden (gold-at p1-2) (pit-at p2-2) (wumpus-at p3-1))
    (:hidden (gold-at p2-1) (pit-at p2-2) (wumpus-at p3-1))
    (:hidden (gold-at p3-2) (pit-at p2-2) (wumpus-at p3-1))
    (:hidden (gold-at p1-1) (pit-at p2-2) (wumpus-at p3-2))
    (:hidden (gold-at p1-2) (pit-at p2-2) (wumpus-at p3-2))
    (:hidden (gold-at p2-1) (pit-at p2-2) (wumpus-at p3-2))
    (:hidden (gold-at p3-1) (pit-at p2-2) (wumpus-at p3-2))
    (:hidden (gold-at p1-1) (pit-at p3-1) (wumpus-at p2-2))
    (:hidden (gold-at p1-2) (pit-at p3-1) (wumpus-at p2-2))
    (:hidden (gold-at p2-1) (pit-at p3-1) (wumpus-at p2-2))
    (:hidden (gold-at p3-2) (pit-at p3-1) (wumpus-at p2-2))
    (:hidden (gold-at p1-1) (pit-at p3-1) (wumpus-at p3-2))
    (:hidden (gold-at p1-2) (pit-at p3-1) (wumpus-at p3-2))
    (:hidden (gold-at p2-1) (pit-at p3-1) (wumpus-at p3-2))
    (:hidden (gold-at p2-2) (pit-at p3-1) (wumpus-at p3-2))
    (:hidden (gold-at p1-1) (pit-at p3-2) (wumpus-at p2-2))
    (:hidden (gold-at p1-2) (pit-at p3-2) (wumpus-at p2-2))
    (:hidden (gold-at p2-1) (pit-at p3-2) (wumpus-at p2-2))
    (:hidden (gold-at p3-1) (pit-at p3-2) (wumpus-at p2-2))
    (:hidden (gold-at p1-1) (pit-at p3-2) (wumpus-at p3-1))
    (:hidden (gold-at p1-2) (pit-at p3-2) (wumpus-at p3-1))
    (:hidden (gold-at p2-1) (pit-at p3-2) (wumpus-at p3-1))
    (:hidden (gold-at p2-2) (pit-at p3-2) (wumpus-at p3-1))
)
