(define (problem p5x5)
    (:hidden (gold-at p3-2) (wumpus-at p2-4) (pit-at p5-1))
    (:hidden (pit-at p2-4) (gold-at p5-4) (wumpus-at p4-3))
    (:hidden (gold-at p3-5) (wumpus-at p1-3) (pit-at p4-1))
    (:hidden (pit-at p5-4) (gold-at p4-3) (wumpus-at p1-4))
    (:hidden (wumpus-at p1-3) (pit-at p5-5) (gold-at p1-1))
)
