(define (problem p7_no_pit)
    (:hidden (wumpus-at p1-3) (gold-at p6-4))
    (:hidden (gold-at p5-6) (wumpus-at p3-3))
    (:hidden (gold-at p5-5) (wumpus-at p6-6))
    ;(:hidden (gold-at p3-5) (wumpus-at p4-5))
    ;(:hidden (wumpus-at p6-6) (gold-at p4-6))
    ;(:hidden (gold-at p2-1) (wumpus-at p3-1))
    ;(:hidden (wumpus-at p4-7) (gold-at p4-3))
    ;(:hidden (gold-at p1-2) (wumpus-at p7-2))
    ;(:hidden (gold-at p1-4) (wumpus-at p2-3))
    ;(:hidden (wumpus-at p4-6) (gold-at p3-7))
    ;(:hidden (gold-at p3-2) (wumpus-at p6-4))
    ;(:hidden (wumpus-at p3-1) (gold-at p4-6))
    ;(:hidden (wumpus-at p7-3) (gold-at p1-5))
    ;(:hidden (wumpus-at p3-7) (gold-at p3-3))
    ;(:hidden (gold-at p3-7) (wumpus-at p5-3))
    ;(:hidden (gold-at p7-6) (wumpus-at p7-2))
    ;(:hidden (wumpus-at p3-6) (gold-at p4-3))
    ;(:hidden (wumpus-at p5-1) (gold-at p6-5))
    ;(:hidden (wumpus-at p1-6) (gold-at p5-6))
    ;(:hidden (wumpus-at p7-2) (gold-at p6-7))
)
