(define (problem p7_no_pit)
    (:hidden (wumpus-at p4-6) (gold-at p5-6))
    (:hidden (gold-at p1-5) (wumpus-at p7-2))
    (:hidden (wumpus-at p4-6) (gold-at p3-5))
    ;(:hidden (gold-at p4-3) (wumpus-at p6-4))
    ;(:hidden (gold-at p2-6) (wumpus-at p6-3))
    ;(:hidden (gold-at p1-1) (wumpus-at p3-7))
    ;(:hidden (gold-at p5-7) (wumpus-at p2-5))
    ;(:hidden (gold-at p6-7) (wumpus-at p6-1))
    ;(:hidden (wumpus-at p6-2) (gold-at p6-4))
    ;(:hidden (gold-at p5-6) (wumpus-at p7-3))
    ;(:hidden (wumpus-at p6-7) (gold-at p3-7))
    ;(:hidden (gold-at p4-4) (wumpus-at p1-5))
    ;(:hidden (gold-at p5-7) (wumpus-at p7-3))
    ;(:hidden (gold-at p1-5) (wumpus-at p7-3))
    ;(:hidden (gold-at p4-3) (wumpus-at p2-6))
    ;(:hidden (wumpus-at p5-5) (gold-at p4-2))
    ;(:hidden (wumpus-at p6-3) (gold-at p4-2))
    ;(:hidden (gold-at p5-2) (wumpus-at p2-5))
    ;(:hidden (gold-at p2-7) (wumpus-at p4-3))
    ;(:hidden (wumpus-at p6-7) (gold-at p5-2))
)
