(define (problem btcs-8-1)
    (:hidden (in p0 b0))
    (:hidden (in p1 b0))
    (:hidden (in p2 b0))
    (:hidden (in p3 b0))
    (:hidden (in p4 b0))
    (:hidden (in p5 b0))
    (:hidden (in p6 b0))
    (:hidden (in p7 b0))
)
