(define (problem lightbulbs2)
    (:hidden (not (light-on r11)) (not (light-on r12)) (not (light-on r21)) (not (light-on r22)))
    (:hidden (not (light-on r11)) (not (light-on r12)) (not (light-on r21)) (light-on r22))
    (:hidden (not (light-on r11)) (not (light-on r12)) (light-on r21) (not (light-on r22)))
    (:hidden (not (light-on r11)) (not (light-on r12)) (light-on r21) (light-on r22))
    (:hidden (not (light-on r11)) (light-on r12) (not (light-on r21)) (not (light-on r22)))
    (:hidden (not (light-on r11)) (light-on r12) (not (light-on r21)) (light-on r22))
    (:hidden (not (light-on r11)) (light-on r12) (light-on r21) (not (light-on r22)))
    (:hidden (not (light-on r11)) (light-on r12) (light-on r21) (light-on r22))
    (:hidden (light-on r11) (not (light-on r12)) (not (light-on r21)) (not (light-on r22)))
    (:hidden (light-on r11) (not (light-on r12)) (not (light-on r21)) (light-on r22))
    (:hidden (light-on r11) (not (light-on r12)) (light-on r21) (not (light-on r22)))
    (:hidden (light-on r11) (not (light-on r12)) (light-on r21) (light-on r22))
    (:hidden (light-on r11) (light-on r12) (not (light-on r21)) (not (light-on r22)))
    (:hidden (light-on r11) (light-on r12) (not (light-on r21)) (light-on r22))
    (:hidden (light-on r11) (light-on r12) (light-on r21) (not (light-on r22)))
    (:hidden (light-on r11) (light-on r12) (light-on r21) (light-on r22))
)
