(define (problem colorballs-3-1)
    (:hidden (color o1 blue) (obj-at o1 p2-1))
    (:hidden (color o1 blue) (obj-at o1 p1-1))
    (:hidden (color o1 blue) (obj-at o1 p1-1))
    (:hidden (obj-at o1 p2-3) (color o1 red))
    (:hidden (color o1 red) (obj-at o1 p2-3))
    (:hidden (obj-at o1 p2-1) (color o1 blue))
    (:hidden (obj-at o1 p1-2) (color o1 blue))
    (:hidden (color o1 red) (obj-at o1 p1-2))
    (:hidden (color o1 red) (obj-at o1 p2-2))
)