(define (problem colorballs-3-1)
    (:hidden (obj-at o2 p3-3) (color o1 red) (obj-at o1 p1-1) (color o2 blue))
    (:hidden (color o2 blue) (obj-at o1 p2-1) (color o1 blue) (obj-at o2 p1-2))
    (:hidden (obj-at o2 p3-1) (color o1 blue) (obj-at o1 p2-3) (color o2 blue))
    (:hidden (obj-at o2 p1-1) (obj-at o1 p3-3) (color o1 blue) (color o2 blue))
    (:hidden (obj-at o1 p2-1) (obj-at o2 p3-3) (color o2 blue) (color o1 red))
    (:hidden (color o2 blue) (obj-at o2 p2-2) (color o1 blue) (obj-at o1 p1-2))
    (:hidden (obj-at o2 p2-3) (color o1 red) (obj-at o1 p3-2) (color o2 blue))
    (:hidden (obj-at o1 p2-1) (color o2 red) (color o1 blue) (obj-at o2 p3-1))
    (:hidden (obj-at o1 p3-1) (color o2 red) (obj-at o2 p2-1) (color o1 blue))
    (:hidden (color o1 blue) (obj-at o1 p1-1) (obj-at o2 p2-3) (color o2 blue))
)
