(define (problem colorballs-3-1)
    (:hidden (color o2 red) (obj-at o1 p3-1) (obj-at o2 p1-2) (color o1 red))
    (:hidden (color o1 blue) (color o2 blue) (obj-at o2 p1-1) (obj-at o1 p1-3))
    (:hidden (color o2 blue) (color o1 red) (obj-at o1 p1-3) (obj-at o2 p3-2))
    ;(:hidden (obj-at o1 p3-1) (obj-at o2 p1-2) (color o2 red) (color o1 red))
    ;(:hidden (color o2 blue) (obj-at o2 p2-3) (color o1 blue) (obj-at o1 p3-2))
    ;(:hidden (color o1 red) (obj-at o2 p2-2) (color o2 red) (obj-at o1 p1-2))
    ;(:hidden (obj-at o1 p1-1) (obj-at o2 p3-2) (color o2 blue) (color o1 red))
    ;(:hidden (color o2 blue) (obj-at o1 p3-3) (color o1 red) (obj-at o2 p2-1))
    ;(:hidden (color o1 red) (obj-at o2 p2-2) (obj-at o1 p1-2) (color o2 red))
    ;(:hidden (color o1 red) (color o2 blue) (obj-at o1 p1-3) (obj-at o2 p3-1))
)
