(define (problem colorballs-5-1)
    (:hidden (color o1 blue) (obj-at o1 p2-4))
    (:hidden (color o1 red) (obj-at o1 p5-3))
    ;(:hidden (color o1 red) (obj-at o1 p2-4))
    ;(:hidden (color o1 red) (obj-at o1 p5-1))
    ;(:hidden (obj-at o1 p3-5) (color o1 blue))
    ;(:hidden (obj-at o1 p3-2) (color o1 red))
    ;(:hidden (color o1 blue) (obj-at o1 p4-4))
    ;(:hidden (color o1 red) (obj-at o1 p3-3))
    ;(:hidden (obj-at o1 p5-2) (color o1 red))
    ;(:hidden (color o1 blue) (obj-at o1 p5-2))
)
