(define (problem colorballs-5-1)
    (:hidden (obj-at o1 p1-4) (color o1 blue))
    (:hidden (color o1 red) (obj-at o1 p5-5))
    (:hidden (obj-at o1 p5-2) (color o1 blue))
    (:hidden (color o1 blue) (obj-at o1 p2-4))
    (:hidden (color o1 red) (obj-at o1 p1-3))
    (:hidden (color o1 blue) (obj-at o1 p4-3))
    ;(:hidden (color o1 red) (obj-at o1 p2-2))
    ;(:hidden (obj-at o1 p2-3) (color o1 red))
    ;(:hidden (color o1 red) (obj-at o1 p5-5))
    ;(:hidden (color o1 blue) (obj-at o1 p4-4))
)
