(define (problem doors4x5)
    (:hidden (opened p2-1) (opened p4-1) (not (opened p2-2)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-2)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-1) (opened p4-2) (not (opened p2-2)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-1) (opened p4-3) (not (opened p2-2)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-4)))
    (:hidden (opened p2-1) (opened p4-4) (not (opened p2-2)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-3)))
    (:hidden (opened p2-2) (opened p4-1) (not (opened p2-1)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-2)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-2) (opened p4-2) (not (opened p2-1)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-2) (opened p4-3) (not (opened p2-1)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-4)))
    (:hidden (opened p2-2) (opened p4-4) (not (opened p2-1)) (not (opened p2-3)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-3)))
    (:hidden (opened p2-3) (opened p4-1) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-4)) (not (opened p4-2)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-3) (opened p4-2) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-3) (opened p4-3) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-4)))
    (:hidden (opened p2-3) (opened p4-4) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-4)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-3)))
    (:hidden (opened p2-4) (opened p4-1) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-3)) (not (opened p4-2)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-4) (opened p4-2) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-3)) (not (opened p4-1)) (not (opened p4-3)) (not (opened p4-4)))
    (:hidden (opened p2-4) (opened p4-3) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-3)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-4)))
    (:hidden (opened p2-4) (opened p4-4) (not (opened p2-1)) (not (opened p2-2)) (not (opened p2-3)) (not (opened p4-1)) (not (opened p4-2)) (not (opened p4-3)))
)
